### ISSUE TITLE
Ingredient collisions

### ISSUE THREAD

**Issue by bchi1** [ucsd-cse125-sp20/cse125-sp20-group2#45]
Ingredient collisions in the dungeon phase don't seem that accurate at the moment, I'm not sure if it has to do with scaling, but the ingredient locations on the client side and the server side seem consistent, and the collisions appear to be handled correctly on the server side.

**Comment by bchi1** [comment]
as an added note, player location on client and server side also appear to be consistent, so more likely due to scaling

**Comment by JMQ0598** [comment]
Fixed. Was an issue with the models being off center.
